---
title: "DSC 385 Schedule"
description: ""
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lectures

### 1. Introduction

<p class="nospace">Materials:</p>

- [Slides](slides/introduction.html)  
- [Worksheet](worksheets/intro-rmarkdown.Rmd)

### 2. Aesthetic mappings

<p class="nospace">Materials:</p>

- [Slides](slides/aesthetic-mappings.html)  
- [Worksheet](worksheets/aesthetic-mappings.Rmd)

### 3. Telling a story

<p class="nospace">Materials:</p>

- [Slides](slides/telling-a-story.html)  

### 4. Visualizing amounts

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-amounts.html)  
- [Worksheet](worksheets/visualizing-amounts.Rmd)

### 5. Coordinate systems and axes

<p class="nospace">Materials:</p>

- [Slides](slides/coordinate-systems-axes.html)  
- [Worksheet](worksheets/coordinate-systems-axes.Rmd)

### 6. Visualizing distributions 1

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-distributions-1.html)  
- [Worksheet](worksheets/visualizing-distributions-1.Rmd)

### 7. Visualizing distributions 2

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-distributions-2.html)  
- [Worksheet](worksheets/visualizing-distributions-2.Rmd)

### 8. Color scales  

<p class="nospace">Materials:</p>

- [Slides](slides/color-scales.html)  
- [Worksheet](worksheets/color-scales.Rmd)

### 9. Data wrangling 1

<p class="nospace">Materials:</p>

- [Slides](slides/data-wrangling-1.html)  
- [Worksheet](worksheets/data-wrangling-1.Rmd)

### 10. Data wrangling 2

<p class="nospace">Materials:</p>

- [Slides](slides/data-wrangling-2.html)  
- [Worksheet](worksheets/data-wrangling-2.Rmd)

### 11. Visualizing proportions 

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-proportions.html)  
- [Worksheet](worksheets/visualizing-proportions.Rmd)

### 12. Getting to know your data 1

<p class="nospace">Materials:</p>

- [Slides](slides/know-your-data-1.html)  
- [Worksheet](worksheets/know-your-data-1.Rmd)

### 13. Getting to know your data 2

<p class="nospace">Materials:</p>

- [Slides](slides/know-your-data-2.html)  
- *Worksheet in preparation*

### 14. Getting things into the right order

<p class="nospace">Materials:</p>

- [Slides](slides/getting-things-in-order.html)  
- [Worksheet](worksheets/getting-things-in-order.Rmd)

### 15. Figure design

<p class="nospace">Materials:</p>

- [Slides](slides/figure-design.html)  
- [Worksheet](worksheets/figure-design.Rmd)

### 16. Color spaces, color vision deficiency

<p class="nospace">Materials:</p>

- [Slides](slides/color-spaces.html)  
- [Worksheet](worksheets/color-spaces.R)

### 17. Functions and functional programming

<p class="nospace">Materials:</p>

- [Slides](slides/functional-programming.html)  
- *Worksheet in preparation*

### 18. Visualizing trends

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-trends.html)  
- [Worksheet](worksheets/visualizing-trends.Rmd)

### 19. Working with models

<p class="nospace">Materials:</p>

- [Slides](slides/working-with-models.html)  
- [Worksheet](worksheets/working-with-models.Rmd)

### 20. Visualizing uncertainty

<p class="nospace">Materials:</p>

- [Slides](slides/visualizing-uncertainty.html)  
- [Worksheet](worksheets/visualizing-uncertainty.Rmd)

### 21. Dimension reduction 1

<p class="nospace">Materials:</p>

- [Slides](slides/dimension-reduction-1.html)  
- [Worksheet](worksheets/dimension-reduction-1.Rmd)

### 22. Dimension reduction 2

<p class="nospace">Materials:</p>

- [Slides](slides/dimension-reduction-2.html)  
- [Worksheet](worksheets/dimension-reduction-2.Rmd)

### 23. Clustering

<p class="nospace">Materials:</p>

- [Slides](slides/clustering.html)  
- [Worksheet](worksheets/clustering.Rmd)

### 24. Hierarchical clustering

<p class="nospace">Materials:</p>

- [Slides](slides/hierarchical-clustering.html)  
- *Worksheet in preparation*

### 25. Data ethics

*Materials in preparation*

### 26. Visualizing geospatial data

<p class="nospace">Materials:</p>

- [Slides](slides/geospatial-data.html)  
- [Worksheet](worksheets/geospatial-data.Rmd)

### 27. Redundant coding

<p class="nospace">Materials:</p>

- [Slides](slides/redundant-coding.html)  
- [Worksheet](worksheets/redundant-coding.Rmd)

### 28. Interactive plots

<p class="nospace">Materials:</p>

- [Slides](slides/interactive-plots.html)  
- [Worksheet](worksheets/interactive-plots.Rmd)

### 29. Dealing with issues of overplotting

<p class="nospace">Materials:</p>

- [Slides](slides/overplotting.html)  
- [Worksheet](worksheets/overplotting.Rmd)

### 30. Compound figures

<p class="nospace">Materials:</p>

- [Slides](slides/compound-figures.html)  
- [Worksheet](worksheets/compound-figures.Rmd)


## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Any computer code (R, HTML, CSS, etc.) in slides and worksheets, including in slide and worksheet sources, is also licensed under [MIT](https://github.com/wilkelab/SDS375/LICENSE.md). Note that figures in slides may be pulled in from external sources and may be licensed under different terms. For such images, image credits are available in the slide notes, accessible via pressing the letter 'p'.
